base_path: "/glade/work/rjarolim/sunerf/2012_01_v01"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf/2012_01_v01"

instruments:
  - type: 'plasma'
    key: 'AIA'
    scaling: { type: 'asinh' }
    temperature_response:
      file: '/glade/work/rjarolim/sunerf/response_v02/aia_response_functions.npz'
      scaling: 0.0
      learnable: True
      normalization: 1.0e-21
      channels: ['A94', 'A131', 'A171', 'A193', 'A211', 'A335']
  - type: 'plasma'
    key: 'EUVI-A'
    scaling: { type: 'asinh' }
    temperature_response:
      file: '/glade/work/rjarolim/sunerf/response_v02/stereo_ahead_response.npz'
      scaling: 0.0
      learnable: False
      normalization: 1.0e+6
      channels: ['171', '195', '284']
  - type: 'plasma'
    key: 'EUVI-B'
    scaling: { type: 'asinh' }
    temperature_response:
      file: '/glade/work/rjarolim/sunerf/response_v02/stereo_behind_response.npz'
      scaling: 0.0
      learnable: False
      normalization: 1.0e+6
      channels: ['171', '195', '284']
data:
  train_datasets:
    - type: 'AIA'
      key: 'AIA'
      instrument_key: 'AIA'
      data_path: '/glade/work/rjarolim/data/sunerf/2012_01_prep/aia/*.fits'
      wavelengths: [94, 131, 171, 193, 211, 335]
    - type: 'EUVI'
      key: 'EUVI-A'
      instrument_key: 'EUVI-A'
      data_path: '/glade/work/rjarolim/data/sunerf/2012_01_prep/euvi/*A.fts'
      wavelengths: [171, 195, 284]
    - type: 'EUVI'
      key: 'EUVI-B'
      instrument_key: 'EUVI-B'
      data_path: '/glade/work/rjarolim/data/sunerf/2012_01_prep/euvi/*B.fts'
      wavelengths: [171, 195, 284]
  valid_datasets:
    - type: 'AIA'
      key: 'AIA'
      instrument_key: 'AIA'
      data_path: '/glade/work/rjarolim/data/sunerf/2012_01_prep/aia/*.fits'
      wavelengths: [94, 131, 171, 193, 211, 335]
    - type: 'EUVI'
      key: 'EUVI-A'
      instrument_key: 'EUVI-A'
      data_path: '/glade/work/rjarolim/data/sunerf/2012_01_prep/euvi/*A.fts'
      wavelengths: [171, 195, 284]
    - type: 'EUVI'
      key: 'EUVI-B'
      instrument_key: 'EUVI-B'
      data_path: '/glade/work/rjarolim/data/sunerf/2012_01_prep/euvi/*B.fts'
      wavelengths: [171, 195, 284]
  debug: False
  batch_size: 4096
  num_workers: 16

logging:
  project: "sunerf"
  name: "2012-01 -AIA + EUVI-A + EUVI-B"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 1.5

shuffle:
  type: "normal_time"
  iterations: 1.0e+5

training:
  log_every_n_steps: 10000

lambda:
  image: 1.0
  regularization: 1.0e-3
  absorption: 0.0