base_path: "/glade/work/rjarolim/sunerf/aia_euvi_2010_06_v01"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf/aia_euvi_2010_06_v01"

instruments:
  - type: 'plasma'
    key: 'AIA'
    scaling: { type: 'asinh' }
    temperature_response:
      file: '/glade/work/rjarolim/sunerf/response_v02/aia_response_functions.npz'
      scaling: 0.0
      learnable: False
      normalization: 1.0e-21
  - type: 'plasma'
    key: 'EUVI-A'
    scaling: { type: 'asinh' }
    temperature_response:
      file: '/glade/work/rjarolim/sunerf/response_v02/stereo_ahead_response.npz'
      scaling: 0.0
      learnable: True
      normalization: 1.0e+6
  - type: 'plasma'
    key: 'EUVI-B'
    scaling: { type: 'asinh' }
    temperature_response:
      file: '/glade/work/rjarolim/sunerf/response_v02/stereo_behind_response.npz'
      scaling: 0.0
      learnable: True
      normalization: 1.0e+6
data:
  train_datasets:
    - type: 'AIA'
      key: 'AIA'
      instrument_key: 'AIA'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/aia/*.fits'
    - type: 'EUVI'
      key: 'EUVI-A'
      instrument_key: 'EUVI-A'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/euvi/*A.fts'
    - type: 'EUVI'
      key: 'EUVI-B'
      instrument_key: 'EUVI-B'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/euvi/*B.fts'
  valid_datasets:
    - type: 'AIA'
      key: 'AIA'
      instrument_key: 'AIA'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/aia/*.fits'
    - type: 'EUVI'
      key: 'EUVI-A'
      instrument_key: 'EUVI-A'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/euvi/*A.fts'
    - type: 'EUVI'
      key: 'EUVI-B'
      instrument_key: 'EUVI-B'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/euvi/*B.fts'
  debug: False
  batch_size: 512
  num_workers: 16

logging:
  project: "sunerf"
  name: "AIA + EUVI-A + EUVI-B"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 1.5

shuffle:
  type: "normal_time"
  start: 10

lambda:
  image: 1.0
  regularization: 1.0e-3
  absorption: 0.0