base_path: "/glade/work/rjarolim/sunerf-cme-obs/2010_03_cor2_correction_v05"
work_directory: '/glade/derecho/scratch/rjarolim/sunerf-cme-obs/2010_03_cor2_correction_v05'

instruments:
  - type: 'default'
    key: 'STEREO_A_COR2'
    scaling: {type: 'log'}
    correction: { corrections: ['f_corona', 'pB_add', 'leakage'] }
  - type: 'default'
    key: 'STEREO_B_COR2'
    scaling: { type: 'log' }
    correction: { corrections: ['f_corona', 'pB_add', 'leakage'] }
    calibration: True

model:
  dim: 128
  static: False
  encoding_config: { type: multi_spectral, weights: [ 30, 30, 30, 1.0 ], num_dims: [32, 32, 32, 4] } #{ type: multi_spectral, weights: [ 10, 10, 10, 1.0e-3 ], num_dims: [32, 32, 32, 4] }
  use_carrington_projection: True

data:
  train_datasets:
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_a_cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_a_cor2/tB/*"
      batch_size: 1024
      debug: False
    - type: 'COR'
      key: 'STEREO_B_COR2'
      instrument_key: 'STEREO_B_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_b_cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_b_cor2/tB/*"
      batch_size: 1024
      debug: False
    - type: 'random'
      name: 'continuity'
      radius_range: [ 2.5, 17.0 ]
      unit: 'solRad'
      batch_size: 4096
  valid_datasets:
    # 1) Standard instrument validation (renders images)
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_a_cor2/pB/20100319_200815_1P4c2A.fts"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_a_cor2/tB/20100319_200815_1B4c2A.fts"

    - type: 'COR'
      key: 'STEREO_B_COR2'
      instrument_key: 'STEREO_B_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_b_cor2/pB/20100319_200815_1P4c2B.fts"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2010_03/prep/stereo_b_cor2/tB/20100319_200815_1B4c2B.fts"


    - key: valid_radial
      type: radial_slices
      radii: [5, 8, 11, 14, 17]
    - type: longitude_slices
      key: valid_lon_slices
      radius_range: [ 2.5, 17.0 ]


  debug: False
  Rs_per_ds: 15
  seconds_per_dt: 86400
  batch_size: 4096
  validation_batch_size: 4096
  num_workers: 16

callbacks:
  # image callbacks
  - type: 'thomson_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'thomson_image'
    ds_key: 'STEREO_B_COR2'
  # correction images
  - type: 'correction_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'correction_image'
    ds_key: 'STEREO_B_COR2'

  - type: radial_slices
    ds_key: valid_radial

  - type: longitude_density
    ds_key: valid_lon_slices

#  - type: longitude_time_density
#    ds_key: valid_lon_time
#    longitudes_deg: [0, 30, 90, 120, 150]  # optional for labels

#  - type: longitude_time_velocitymag
#    ds_key: valid_lon_time

#  - type: fixed_viewpoint_series
#    ds_key: valid_view
#    n_times: 6  # optional if dataset exposes base.n_times

#  - type: star_background_full
#    ds_key: valid_star_bg
#    eps: 1e-12


logging:
  entity: "robert_jarolim"
  project: "sunerf-cme-obs"
  name: "2010-03 - COR2 - correction"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 17.0

lambda:
  image: 1.0
  ratio: 10.0
  radial: 1.0e-4
  continuity: 1.0e-6
  velocity: 1.0e-4


training:
  log_every_n_steps: 10000