base_path: "/glade/work/rjarolim/sunerf-cme-obs/201208_cor2_static_v01"
work_directory: '/glade/derecho/scratch/rjarolim/sunerf-cme-obs/201208_cor2_v03'

instruments:
  - type: 'default'
    key: 'STEREO_A_COR2'
    scaling: {type: 'log'}
    correction: { corrections: [ 'pB_add', 'tB_add' ] }
    calibration: False
    alignment: False
  - type: 'default'
    key: 'STEREO_B_COR2'
    scaling: { type: 'log' }
    correction: { corrections: [ 'pB_add', 'tB_add' ] }
    calibration: True
    alignment: False

model:
  dim: 128
  static: True
  input_weights: [30, 30, 30]
  w0_init: 1.0
  use_carrington_projection: True

data:
  train_datasets:
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_a_cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_a_cor2/tB/*"
      batch_size: 1024
      debug: False
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/masks/stereo_a_cor2_tB_correction.npy", alpha: 0.8, clean: False }
    - type: 'COR'
      key: 'STEREO_B_COR2'
      instrument_key: 'STEREO_B_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_b_cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_b_cor2/tB/*"
      batch_size: 1024
      debug: False
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/masks/stereo_b_cor2_tB_correction.npy", alpha: 0.8, clean: False }
    - type: 'random'
      name: 'continuity'
      radius_range: [ 1.5, 17.0 ]
      unit: 'solRad'
      batch_size: 4096
  valid_datasets:
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_a_cor2/pB/20120815_100815_1P4c2A.fts"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_a_cor2/tB/20120815_100815_1B4c2A.fts"
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/masks/stereo_a_cor2_tB_correction.npy", alpha: 0.8, clean: False }
    - type: 'COR'
      key: 'STEREO_B_COR2'
      instrument_key: 'STEREO_B_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_b_cor2/pB/20120815_100815_1P4c2B.fts"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/stereo_b_cor2/tB/20120815_100815_1B4c2B.fts"
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2012_08/prep/masks/stereo_b_cor2_tB_correction.npy", alpha: 0.8, clean: False }

    - key: valid_radial
      type: radial_slices
      radii: [3, 6, 9, 12, 15]

    - type: longitude_slices
      key: valid_lon_slices
      radius_range: [2.5, 15.0]
  debug: False
  Rs_per_ds: 15
  seconds_per_dt: 100000
  batch_size: 4096
  validation_batch_size: 4096
  num_workers: 16

callbacks:
  # image callbacks
  - type: 'thomson_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'thomson_image'
    ds_key: 'STEREO_B_COR2'
  # correction images
  - type: 'correction_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'correction_image'
    ds_key: 'STEREO_B_COR2'

  - type: radial_slices
    ds_key: valid_radial

  - type: longitude_density
    ds_key: valid_lon_slices

logging:
  entity: "robert_jarolim"
  project: "sunerf-cme-obs-v2"
  name: "2012-08 - COR2 - static"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 17.0

lambda:
  image: 1.0
  ratio: 10.0
  radial: 1.0e-2
  continuity: 1.0e-2
  velocity: 1.0e-2

training:
  log_every_n_steps: 2000