base_path: "/glade/work/rjarolim/sunerf-cme-obs/202409_cor2_metis_v06"
work_directory: '/glade/derecho/scratch/rjarolim/sunerf-cme-obs/202409_cor2_metis_v06'

instruments:
  - type: 'default'
    key: 'Metis'
    scaling: { type: 'log' }
    correction: { corrections: [ 'f_corona', 'calibration' ] }
  - type: 'default'
    key: 'COR2'
    scaling: { type: 'log' }
    correction: { corrections: [ 'f_corona' ] }

model:
  dim: 128
  static: False
  encoding_config: { type: multi_spectral, weights: [ 30, 30, 30, 1.0 ], num_dims: [32, 32, 32, 4] }

data:
  train_datasets:
    - type: 'Metis'
      key: 'Metis'
      instrument_key: 'Metis'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/metis/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/metis/tB/*"
      batch_size: 1024
      debug: False
    - type: 'COR'
      key: 'COR2'
      instrument_key: 'COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/cor2/tB/*"
      batch_size: 1024
      debug: False
#    - type: 'random'
#      name: 'continuity'
#      radius_range: [ 1.5, 17.0 ]
#      unit: 'solRad'
#      batch_size: 4096
  valid_datasets:
    - type: 'COR'
      key: 'COR2'
      instrument_key: 'COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/cor2/pB/20240915_000745_1P4c2A.fts"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/cor2/tB/20240915_000745_1B4c2A.fts"
    - type: 'Metis'
      key: 'Metis'
      instrument_key: 'Metis'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/metis/pB/solo_L2_metis-vl-pb_20240915T003001_V01.fits"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2024_10/prep/metis/tB/solo_L2_metis-vl-tb_20240915T003001_V01.fits"

    - key: valid_radial
      type: radial_slices
      radii: [2, 6, 10, 14, 18]
    - type: longitude_slices
      key: valid_lon_slices
      radius_range: [ 1.5, 17.0 ]
  debug: False
  Rs_per_ds: 15
  seconds_per_dt: 86400
  batch_size: 4096
  validation_batch_size: 4096
  num_workers: 16

callbacks:
  # image callbacks
  - type: 'thomson_image'
    ds_key: 'COR2'
  - type: 'thomson_image'
    ds_key: 'Metis'
  # correction images
  - type: 'correction_image'
    ds_key: 'COR2'
  - type: 'correction_image'
    ds_key: 'Metis'

  - type: radial_slices
    ds_key: valid_radial

  - type: longitude_density
    ds_key: valid_lon_slices

logging:
  entity: "robert_jarolim"
  project: "sunerf-cme-obs"
  name: "2024-10 - COR2 + Metis"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 17.0

lambda:
  image: 1.0
  ratio: 10.0
#  radial: 1.0e-4
#  continuity: 1.0e-4
#  velocity: 1.0e-4

training:
  log_every_n_steps: 10000