base_path: "/glade/work/rjarolim/sunerf-cme-obs/2025_09_cor2_ccor_v03"
work_directory: '/glade/derecho/scratch/rjarolim/sunerf-cme-obs/2025_09_cor2_ccor_v03'

instruments:
  - type: 'default'
    key: 'STEREO_A_COR2'
    scaling: { type: 'log' }
    correction: { corrections: [ 'f_corona', 'pB_straylight' ] }
  - type: 'default'
    key: 'CCOR'
    scaling: { type: 'log' }
    correction: { corrections: [ 'f_corona' ] }
    calibration: True

model:
  dim: 128
  static: False
  encoding_config: { type: multi_spectral, weights: [ 30, 30, 30, 1.0 ], num_dims: [ 32, 32, 32, 4 ] }
  use_carrington_projection: True

data:
  train_datasets:
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/cor2/tB/*"
      batch_size: 1024
      debug: False
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/masks/stereo_a_cor2_tB_correction.npy", alpha: 0.8, clean: False }

    - type: 'CCOR'
      key: 'CCOR'
      instrument_key: 'CCOR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/ccor/*"
      batch_size: 1024
      debug: False
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/masks/ccor_tB_correction.npy", alpha: 0.8, clean: False }

    - type: 'random'
      name: 'continuity'
      radius_range: [ 2.5, 30.0 ]
      unit: 'solRad'
      batch_size: 4096

  valid_datasets:
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/cor2/tB/*"
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/masks/stereo_a_cor2_tB_correction.npy", alpha: 0.8, clean: False }

    - type: 'CCOR'
      key: 'CCOR'
      instrument_key: 'CCOR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/ccor/*"
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2025_09/prep/masks/ccor_tB_correction.npy", alpha: 0.8, clean: False }

    - key: valid_radial
      type: radial_slices
      radii: [ 3, 6, 9, 12, 15 ]

    - type: longitude_slices
      key: valid_lon_slices
      radius_range: [ 2.5, 20.0 ]

  Rs_per_ds: 15
  seconds_per_dt: 86400
  batch_size: 4096
  validation_batch_size: 4096
  num_workers: 16

callbacks:
  - type: 'thomson_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'thomson_image'
    ds_key: 'CCOR'

  - type: 'correction_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'correction_image'
    ds_key: 'CCOR'

  - type: radial_slices
    ds_key: valid_radial

  - type: longitude_density
    ds_key: valid_lon_slices

logging:
  entity: "robert_jarolim"
  project: "sunerf-cme-obs"
  name: "2025-09 - STEREO A COR2 + CCOR"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 25.0

lambda:
  image: 1.0
  ratio: 10.0
  radial: 1.0e-2
  continuity: 1.0e-2
  velocity: 1.0e-2

training:
  log_every_n_steps: 2000
