base_path: "/glade/work/rjarolim/sunerf-cme-obs/2026_04_v04"
work_directory: '/glade/derecho/scratch/rjarolim/sunerf-cme-obs/2026_04_v03'

instruments:
  - type: 'default'
    key: 'STEREO_A_COR2'
    scaling: { type: 'asinh', a: 1.0e-3 }
    correction: { corrections: [ 'f_corona', 'pB_add', 'tB_add', 'pB_mul', 'tB_mul' ] }
  - type: 'default'
    key: 'STEREO_A_COR2_CLEAR'
    scaling: { type: 'asinh', a: 1.0e-3 }
    correction: { corrections: [ 'f_corona', 'tB_add', 'tB_mul' ] }
  - type: 'default'
    key: 'CCOR'
    scaling: { type: 'asinh', a: 1.0e-3 }
    correction: { corrections: [ 'f_corona', 'tB_add', 'tB_mul' ] }

model:
  use_carrington_projection: True

data:
  train_datasets:
    # Background datasets
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2/pB/*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2/tB/*"
      batch_size: 1024
      debug: False
      correction_config: { type: file,
                           tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_tB_correction.npy",
                           pB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_pB_correction.npy",
                           clean: False }

    - type: 'COR'
      key: 'STEREO_A_COR2_CLEAR'
      instrument_key: 'STEREO_A_COR2_CLEAR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2_clear/*"
      batch_size: 1024
      debug: False
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_tB_clear_correction.npy", clean: False }

    - type: 'CCOR'
      key: 'CCOR'
      instrument_key: 'CCOR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/ccor/*"
      batch_size: 1024
      debug: False

    # CME time datasets
    - type: 'COR'
      key: 'STEREO_A_COR2_CME'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2/pB/20260423_*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2/tB/20260423_*"
      batch_size: 256
      debug: False
      correction_config: { type: file,
                           tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_tB_correction.npy",
                           pB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_pB_correction.npy",
                           clean: False }

    - type: 'COR'
      key: 'STEREO_A_COR2_CLEAR_CME'
      instrument_key: 'STEREO_A_COR2_CLEAR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2_clear/20260423_*"
      batch_size: 256
      debug: False
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_tB_clear_correction.npy", clean: False }

    - type: 'CCOR'
      key: 'CCOR_CME'
      instrument_key: 'CCOR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/ccor/sci_ccor1-l2_g19_s20260423T*_e20260423T*_p*_pub.fits"
      batch_size: 256
      debug: False

    - type: 'random'
      name: 'continuity'
      radius_range: [ 1.5, 27.0 ]
      unit: 'solRad'
      batch_size: 4096
      volume_uniform_sampling: True

  valid_datasets:
    - type: 'COR'
      key: 'STEREO_A_COR2'
      instrument_key: 'STEREO_A_COR2'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2/pB/20260423_19*"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2/tB/20260423_19*"
      correction_config: { type: file,
                           tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_tB_correction.npy",
                           pB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_pB_correction.npy",
                           clean: False }

    - type: 'COR'
      key: 'STEREO_A_COR2_CLEAR'
      instrument_key: 'STEREO_A_COR2_CLEAR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/cor2_clear/20260423_19*"
      correction_config: { type: file, tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/masks/stereo_a_cor2_tB_clear_correction.npy", clean: False }

    - type: 'CCOR'
      key: 'CCOR'
      instrument_key: 'CCOR'
      data_path_pB: null
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/2026_04/prep/ccor/sci_ccor1-l2_g19_s20260408T134525Z_e20260408T134553Z_p20260423T103019Z_pub.fits"

    - key: valid_radial
      type: radial_slices
      radii: [3, 6, 9, 12, 15]
      n_times: 5

    - type: longitude_slices
      key: valid_lon_slices
      radius_range: [2.0, 22.0]
      n_times: 5

  Rs_per_ds: 20
  seconds_per_dt: 86400
  batch_size: 4096
  validation_batch_size: 4096
  num_workers: 32

callbacks:
  - type: 'thomson_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'thomson_image'
    ds_key: 'STEREO_A_COR2_CLEAR'
  - type: 'thomson_image'
    ds_key: 'CCOR'

  - type: 'correction_image'
    ds_key: 'STEREO_A_COR2'
  - type: 'correction_image'
    ds_key: 'STEREO_A_COR2_CLEAR'
  - type: 'correction_image'
    ds_key: 'CCOR'

  - type: radial_slices
    ds_key: valid_radial

  - type: longitude_density
    ds_key: valid_lon_slices

logging:
  entity: "robert_jarolim"
  project: "sunerf-cme-obs-v4"
  name: "2026-04 to 2026-05 - STEREO A COR2 + CCOR"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 25.0
  radial_weighting: False

lambda:
  image: 1.0
  ratio: 1.0
  radial: 1.0e-4
  continuity: 1.0e-3
  velocity: 1.0e-1

training:
  log_every_n_steps: 10000
