base_path: "/glade/work/rjarolim/sunerf-cme-v2/cme1_2view_v02"
work_directory: '/glade/derecho/scratch/rjarolim/sunerf-cme-v2/cme1_2view_v02'

instruments:
  - type: 'default'
    key: 'HAO'
    scaling: {type: 'log'}

model:
  dim: 512

data:
  train_datasets:
    - type: 'HAO'
      key: 'HAO'
      instrument_key: 'HAO'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/cme1/prep_2view/*pB*.fits"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/cme1/prep_2view/*tB*.fits"
      batch_size: 2048
    - type: 'random'
      name: 'continuity'
      radius_range: [ 20, 140 ]
      unit: 'solRad'
      batch_size: 1024
  valid_datasets:
    - type: 'HAO'
      key: 'HAO_sample'
      instrument_key: 'HAO'
      data_path_pB: "/glade/work/rjarolim/data/sunerf-cme/cme1/prep_2view/cme1_dcmer_030E_bang_0000_pB_stepnum_030.fits"
      data_path_tB: "/glade/work/rjarolim/data/sunerf-cme/cme1/prep_2view/cme1_dcmer_030E_bang_0000_tB_stepnum_030.fits"
    - type: 'series'
      name: 'series'
      batch_size: 16384
  debug: False
  Rs_per_ds: 100
  seconds_per_dt: 100000
  batch_size: 4096
  validation_batch_size: 4096
  num_workers: 16

callbacks:
  - type: 'thomson_image'
    ds_key: 'HAO_sample'
  - type: 'velocity_slice'
    name: 'velocity_slice'
    ds_key: 'series'
    latitude: 0

logging:
  entity: "robert_jarolim"
  project: "sunerf-cme"
  name: "CME 1 - 2view"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 140

lambda:
  image: 1.0
  ratio: 1.0
  radial: 1.0e-2
  continuity: 1.0e-2
  velocity: 1.0e-2

training:
  check_val_every_n_epoch: 10