base_path: "/glade/work/rjarolim/sunerf-conditioned/aia_193_v03"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf-conditioned/aia_193_v01"

data:
  data_path: '/glade/work/rjarolim/data/sunerf-conditioned/aia_193_npz/*.npz'
  patch_size: null
  batch_size: 16
  n_rays: 512
  num_workers: 32
  cmap: 'sdoaia193'

logging:
  project: "sunerf-conditioned"
  name: "AIA - 193 A"

sampling:
  type: "spherical"
  n_samples: 64
  max_distance: 1.4

lambda:
  image: 1.0

training:
  check_val_every_n_epoch: 50