base_path: "/glade/work/rjarolim/sunerf/all_2010_06_v02"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf/all_2010_06_v02"

data:
  data_config:
    - type: 'AIA'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/aia/*.fits'
      wavelengths: [94, 131, 171, 193, 211, 335]
    - type: 'EUVI'
      key: 'EUVI-A'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/euvi/*A.fts'
      wavelengths: [171, 195, 284]
    - type: 'EUVI'
      key: 'EUVI-B'
      data_path: '/glade/work/rjarolim/data/sunerf/2010_06_prep/euvi/*B.fts'
      wavelengths: [171, 195, 284]
  debug: False
  batch_size: 512
  num_workers: 16

logging:
  project: "sunerf"
  name: "2010-06"

training:
  log_every_n_steps: 2000

model:
  image_scaling_config:
    AIA: { vmax: 1.0 }
    EUVI-A: { vmax: 1.0 }
    EUVI-B: { vmax: 1.0 }
  temperature_response_config:
    AIA: { file: '/glade/work/rjarolim/sunerf/response/aia_thin_interpolated.npz', scaling: 0.0, n_channels: 7, learnable: False }
    EUVI-A: { file: '/glade/work/rjarolim/sunerf/response/stereo_ahead_thin_interpolated.npz', scaling: 0.0, n_channels: 4, learnable: True }
    EUVI-B: { file: '/glade/work/rjarolim/sunerf/response/stereo_behind_thin_interpolated.npz', scaling: 0.0, n_channels: 4, learnable: True }

