base_path: "/glade/work/rjarolim/sunerf/filament_v01"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf/filament_v01"

data:
  data_config:
    - type: 'AIA'
      data_path: '/glade/work/rjarolim/data/sunerf/2023_03/filament/aia/*.fits'
      static: True
  debug: False
  batch_size: 512
  num_workers: 16

logging:
  project: "sunerf"
  name: "2023-03 filament"

training:
  log_every_n_steps: 10000

model:
  image_scaling_config:
    AIA: { vmax: 1.0 }
  temperature_response_config:
    AIA: { file: '/glade/work/rjarolim/sunerf/response/aia_interpolated.npz', scaling: 0.0, n_channels: 7, learnable: False }
  opacity_config: True
  sampling_config: {type: 'spherical', distance: 1.5}

