base_path: "/glade/work/rjarolim/sunerf/2023_04_combined_v05"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf/2023_04_combined_v05"

data:
  data_config:
    - type: 'AIA'
      key: 'AIA_FD'
      data_path: '/glade/work/rjarolim/data/sunerf/2023_04/prep/aia_fd/*.fits'
      batch_size: 256
#    - type: 'AIA'
#      key: 'AIA_SUB'
#      data_path: '/glade/work/rjarolim/data/sunerf/2023_04/prep/aia_sub/*.fits'
#      batch_size: 128
    - type: 'EUI'
      key: 'EUI_FD'
      data_path: '/glade/work/rjarolim/data/sunerf/2023_04/prep/eui_fd/*.fits'
      batch_size: 256
#    - type: 'EUI'
#      key: 'EUI_SUB'
#      data_path: '/glade/work/rjarolim/data/sunerf/2023_04/prep/eui_sub/*.fits'
#      batch_size: 128
  random_config:
    radius_range: [1.0, 2.5]
    batch_size: 512
  debug: False
  batch_size: 512
  validation_batch_size: 1024
  num_workers: 16

logging:
  project: "sunerf"
  name: "2023-04 combined"

training:
  log_every_n_steps: 10000

model:
  model_config:
    dim: 512
  image_scaling_config:
    AIA_FD: { vmax: 1.0 }
    AIA_SUB: { vmax: 1.0 }
    EUI_FD: { vmax: 1.0 }
    EUI_SUB: { vmax: 1.0 }
  temperature_response_config:
    - file: '/glade/work/rjarolim/sunerf/response/aia_interpolated.npz'
      scaling: 0.0
      learnable: False
      instruments: ['AIA_FD', 'AIA_SUB']
    - file: '/glade/work/rjarolim/sunerf/response/eui_interpolated.npz'
      scaling: 0.03677
      learnable: True
      instruments: ['EUI_FD', 'EUI_SUB']
  shuffle_config:
    type: 'time'
    probability: 0.5
    instruments: ['AIA_FD', 'EUI_FD']
  sampling_config: {type: 'spherical', distance: 2.5}

